### ISSUE TITLE
DLiteMetaModel does not support a metadata without dimension.

### ISSUE THREAD

**Issue by terence-coudert** [SINTEF/dlite#44]
I have created a new test for the fortran bindings, with a new metadata Animal.json where the dimensions array is empty. This entity contains only 2 string properties without dimensions.
When the DLiteMeta is created from the DLiteMetaModel I got this error:

 test_animal.f90: create animals
** Error 1: Missing value for "dimensions" in metadata model: http://meta.sintef.no/0.1/Animal

The code is in branch fortran-bindings, commit d9027c681f76bb7bade88e648c55dd4d2d494cb6

**Comment by jesper-friis** [comment]
Hmm, when compiling with gfortran I get the following errors:

[ 88%] Generate /home/friisj/prosjekter/software/dlite/build/bindings/fortran/tests/Animal.f90
Scanning dependencies of target Animal
[ 88%] Building Fortran object bindings/fortran/tests/CMakeFiles/Animal.dir/Animal.f90.o
/home/friisj/prosjekter/software/dlite/build/bindings/fortran/tests/Animal.f90:142:22:

  142 |                     [], &
      |                      1
Error: Empty array constructor at (1) is not allowed
/home/friisj/prosjekter/software/dlite/build/bindings/fortran/tests/Animal.f90:78:2:

   78 |   function create32() result(animal)
      |  1
......
   91 |   function create64() result(animal)
      |  2
Error: Ambiguous interfaces in generic interface 'tanimal' for ‘create32’ at (1) and ‘create64’ at (2)


From the first error, it seems that we have to treat zero dimensions as a special case since Fortran doesn't support empty array constructors. Or can this be fixed by requireing a later version of Fortran?

From the second error, it seems that we cannot define both create32() and create64(). If I comment one out, the compiler stops complaining. Is there any reason while both functions are defined?

Regards
/Jesper

________________________________

**Comment by terence-coudert** [comment]
It seems that you are using an old fortran template for dlite-genertor. this should be fixed in the commit of the previous comment. You need to update your dlite install, otherwise the generator use an old version of the template.

**Comment by jesper-friis** [comment]
Unfortunately. It doesn't seem to work. After commenting out the animal test, running 'make install' and readding the animal test, I get the exact same error.

Is the updated template in the fortran-bindings branch?

**Comment by terence-coudert** [comment]
ok I will check. But could you check the ctest? The gihub-ci has failed on one test (it's not a fortran test). If you build WITH_FORTRAN=OFF...

**Comment by terence-coudert** [comment]
The fortran template is up-to-date in the branch fortran-bindings. For example, the template should contains the code (from line 63)
{@if:{_ndimensions}>0}
      ! create a {name} and allocate the arrays (type of dimensions: integer(8))
      module procedure create64
{@endif}

**Comment by jesper-friis** [comment]
Thanks. I will take a look at the test

**Comment by terence-coudert** [comment]
Fixed in commit 4435730e341f3dc42ea28f8d58d377ecd2b6e19f
