### ISSUE TITLE
Error in documentation and asdict

### ISSUE THREAD

**Issue by sygout** [SINTEF/dlite#811]
In the documentation it is specified: uri: An optional unique name identifying the instance

But a dictionary without that key cannot be load from a json file.

The function asdict produces a dictionary that does not contain uri but uuid.

**Comment by jesper-friis** [comment]
Agree, it might be little confusing. SOFT5 had slightly different ways to serialise entities and instances as JSON, which DLite inherited. In DLite we call these two serialisation forms for *single-entity form* (entities) and *multi-entity form* (instances).

The `asdict()` method has a boolean option called `single` for selecting which serialisation form to use. The default value is True, which was an unfortunate choice, since not all plugins supports parsing instances in single-entity form.

PR #833 changes the default to single-entity form for entities and multi-entity form for instances. This may be easier to use, but changes the behaviour of DLite and may break existing code.

An alternative would be to always use the more general multi-entity form as the default.

**Comment by sygout** [comment]
I think that it is necessary to clarify what DLite is supposed to do before aligning one way or the other. As it might be a breaking change, it would require a new version and so it might be worth considering what that version should look like.
